/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface SendCAMInterface extends ethers.utils.Interface {
  functions: {
    "getAllTransactions()": FunctionFragment;
    "getTransactionCount()": FunctionFragment;
    "transfer(address,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAllTransactions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTransactionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllTransactions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTransactionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;

  events: {
    "Transfer(address,address,uint256,string,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
}

export type TransferEvent = TypedEvent<
  [string, string, BigNumber, string, BigNumber] & {
    from: string;
    receiver: string;
    amount: BigNumber;
    message: string;
    timestamp: BigNumber;
  }
>;

export class SendCAM extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SendCAMInterface;

  functions: {
    getAllTransactions(
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, string, BigNumber, string, BigNumber] & {
          sender: string;
          receiver: string;
          amount: BigNumber;
          message: string;
          timestamp: BigNumber;
        })[]
      ]
    >;

    getTransactionCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    transfer(
      _to: string,
      _message: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getAllTransactions(
    overrides?: CallOverrides
  ): Promise<
    ([string, string, BigNumber, string, BigNumber] & {
      sender: string;
      receiver: string;
      amount: BigNumber;
      message: string;
      timestamp: BigNumber;
    })[]
  >;

  getTransactionCount(overrides?: CallOverrides): Promise<BigNumber>;

  transfer(
    _to: string,
    _message: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getAllTransactions(
      overrides?: CallOverrides
    ): Promise<
      ([string, string, BigNumber, string, BigNumber] & {
        sender: string;
        receiver: string;
        amount: BigNumber;
        message: string;
        timestamp: BigNumber;
      })[]
    >;

    getTransactionCount(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      _to: string,
      _message: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Transfer(address,address,uint256,string,uint256)"(
      from?: null,
      receiver?: null,
      amount?: null,
      message?: null,
      timestamp?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string, BigNumber],
      {
        from: string;
        receiver: string;
        amount: BigNumber;
        message: string;
        timestamp: BigNumber;
      }
    >;

    Transfer(
      from?: null,
      receiver?: null,
      amount?: null,
      message?: null,
      timestamp?: null
    ): TypedEventFilter<
      [string, string, BigNumber, string, BigNumber],
      {
        from: string;
        receiver: string;
        amount: BigNumber;
        message: string;
        timestamp: BigNumber;
      }
    >;
  };

  estimateGas: {
    getAllTransactions(overrides?: CallOverrides): Promise<BigNumber>;

    getTransactionCount(overrides?: CallOverrides): Promise<BigNumber>;

    transfer(
      _to: string,
      _message: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getAllTransactions(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTransactionCount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transfer(
      _to: string,
      _message: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
