/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AccessControl } from "./AccessControl";
export type { IAccessControl } from "./IAccessControl";
export type { Ownable } from "./Ownable";
export type { ERC1155 } from "./ERC1155";
export type { IERC1155MetadataURI } from "./IERC1155MetadataURI";
export type { IERC1155 } from "./IERC1155";
export type { IERC1155Receiver } from "./IERC1155Receiver";
export type { ERC20 } from "./ERC20";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { IERC20 } from "./IERC20";
export type { ERC721 } from "./ERC721";
export type { IERC721Metadata } from "./IERC721Metadata";
export type { IERC721 } from "./IERC721";
export type { IERC721Receiver } from "./IERC721Receiver";
export type { ERC165 } from "./ERC165";
export type { IERC165 } from "./IERC165";
export type { IAdmin } from "./IAdmin";
export type { KYCTest } from "./KYCTest";
export type { Staking } from "./Staking";
export type { TestToken } from "./TestToken";

export { AccessControl__factory } from "./factories/AccessControl__factory";
export { IAccessControl__factory } from "./factories/IAccessControl__factory";
export { Ownable__factory } from "./factories/Ownable__factory";
export { ERC1155__factory } from "./factories/ERC1155__factory";
export { IERC1155MetadataURI__factory } from "./factories/IERC1155MetadataURI__factory";
export { IERC1155__factory } from "./factories/IERC1155__factory";
export { IERC1155Receiver__factory } from "./factories/IERC1155Receiver__factory";
export { ERC20__factory } from "./factories/ERC20__factory";
export { IERC20Metadata__factory } from "./factories/IERC20Metadata__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
export { ERC721__factory } from "./factories/ERC721__factory";
export { IERC721Metadata__factory } from "./factories/IERC721Metadata__factory";
export { IERC721__factory } from "./factories/IERC721__factory";
export { IERC721Receiver__factory } from "./factories/IERC721Receiver__factory";
export { ERC165__factory } from "./factories/ERC165__factory";
export { IERC165__factory } from "./factories/IERC165__factory";
export { IAdmin__factory } from "./factories/IAdmin__factory";
export { KYCTest__factory } from "./factories/KYCTest__factory";
export { Staking__factory } from "./factories/Staking__factory";
export { TestToken__factory } from "./factories/TestToken__factory";
